Univer/Application/Adm/Controllers/DadosBasicos/ArbitragensController.cs
#region Bibliotecas

//Identyty

//Entity
using Core.Entities;
using Helpers;
using Newtonsoft.Json;
//Models Local

//Lista
using PagedList;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Globalization;
//Excel
using System.Threading;
using System.Web.Mvc;

#endregion

namespace Sistema.Controllers
{
    [Authorize(Roles = "Master, perfilAdministrador")]
    public class ArbitragensController : Controller
    {
        #region Variaveis

        private YLEVELEntities db = new YLEVELEntities();
        private Core.Helpers.TraducaoHelper traducaoHelper;

        #endregion

        #region Mensagem

        public void Mensagem(string titulo, string[] mensagem, string tipo)
        {
            Session["strPoppup"] = tipo;
            Session["strMensagem"] = mensagem;
            Session["strTitulo"] = titulo;
        }

        public void obtemMensagem()
        {
            string strErr = "NOOK";
            string strAle = "NOOK";
            string strMsg = "NOOK";
            string strTipo = "";

            if (Session["strPoppup"] != null)
            {
                strTipo = Session["strPoppup"].ToString();
            }

            switch (strTipo)
            {
                case "err":
                    strErr = "OK";
                    break;
                case "ale":
                    strAle = "OK";
                    break;
                case "msg":
                    strMsg = "OK";
                    break;
            }

            ViewBag.PopupErr = strErr;
            ViewBag.PopupMsg = strMsg;
            ViewBag.PopupAlert = strAle;

            ViewBag.PopupTitle = Session["strTitulo"];
            ViewBag.PopupMessage = Session["strMensagem"];

            Session["strPoppup"] = "NOOK";
            Session["strTitulo"] = "";
            Session["strMensagem"] = "";
        }
        #endregion

        #region Helpers

        private void Localizacao()
        {
            Core.Entities.Idioma idioma = Local.UsuarioIdioma;

            ViewBag.TraducaoHelper = new Core.Helpers.TraducaoHelper(idioma);
            var culture = new System.Globalization.CultureInfo("en-US");  //var culture = new System.Globalization.CultureInfo("en-US");  //var culture = new System.Globalization.CultureInfo(idioma.Sigla);
            traducaoHelper = new Core.Helpers.TraducaoHelper(idioma);
            Thread.CurrentThread.CurrentCulture = culture;
            Thread.CurrentThread.CurrentUICulture = culture;
        }

        public class LAssoc
        {
            public string dtInicio { get; set; }
            public string dtfim { get; set; }
            public LArbitragem[] itens { get; set; }
        }
        public class LArbitragem
        {
            public string id { get; set; }
            public string arbitragemPeriodo { get; set; }
            public string nivelAssoc { get; set; }
            public string percSeg { get; set; }
            public string percTer { get; set; }
            public string percQua { get; set; }
            public string percQui { get; set; }
            public string percSex { get; set; }
        }

        #endregion

        #region Actions
        // GET: Blocos
        public ActionResult Index(string SortOrder,
                                  string CurrentProcuraData, string ProcuraData,
                                  string CurrentProcuraValor, string ProcuraValor,
                                  int? NumeroPaginas, int? Page)
        {
            Localizacao();

            //Verifica se a msg em popup para ser exibido na view
            obtemMensagem();

            //Persistencia dos paramentros da tela
            Funcoes objFuncoes = new Funcoes(this.HttpContext);
            objFuncoes.Persistencia(ref SortOrder,
                                    ref CurrentProcuraData,
                                    ref ProcuraData,
                                    ref CurrentProcuraValor,
                                    ref ProcuraValor,
                                    ref NumeroPaginas,
                                    ref Page,
                                    "Arbitragem");
            objFuncoes = null;

            //List
            if (String.IsNullOrEmpty(SortOrder))
            {
                ViewBag.CurrentSort = "name_desc";
            }
            else
            {
                ViewBag.CurrentSort = SortOrder;
            }

            if (!(ProcuraData != null || ProcuraValor != null))
            {
                if (ProcuraData == null)
                {
                    ProcuraData = CurrentProcuraData;
                }
                if (ProcuraValor == null)
                {
                    ProcuraValor = CurrentProcuraValor;
                }
            }

            ViewBag.CurrentProcuraNome = ProcuraData;
            ViewBag.CurrentProcuraEndereco = ProcuraValor;

            IQueryable<ArbitragemPeriodo> lista = db.ArbitragemPeriodo;
            //var dic = db.Arbitragem.GroupBy(g => g.DataInicio, v => v).ToDictionary(k => k.Key, value => value.ToList());

            // var dic = db.Arbitragem.GroupBy(g => g.DataInicio, v => v).ToDictionary(k => k.Key, value => value.ToList());
            // dic[0].First().DataFim
            //var a = lista.Select(s => new {s.DataInicio}).Distinct().ToList<DateTime>();
            // ViewBag.Dist = lista.Select(s => new { s.DataInicio, s.DataFim }).Distinct();


            if (!String.IsNullOrEmpty(ProcuraData))
            {
                var data = Convert.ToDateTime(ProcuraData);
                lista = lista.Where(s => s.DataInicio <= data && s.DataFim >= data);
            }

            switch (SortOrder)
            {
                case "name_desc":
                    ViewBag.NameSortParm = "name";
                    ViewBag.DateSortParm = "date";
                    lista = lista.OrderByDescending(s => s.DataInicio);
                    break;
                case "name":
                    ViewBag.NameSortParm = "name_desc";
                    ViewBag.DateSortParm = "date";

                    lista = lista.OrderBy(s => s.DataInicio);
                    break;
                default:  // Name Descending 
                    ViewBag.NameSortParm = "name";
                    ViewBag.DateSortParm = "date";
                    lista = lista.OrderByDescending(s => s.DataInicio);
                    break;
            }

            //Numero de linhas por Pagina
            int PageSize = (NumeroPaginas ?? 5);

            //Caso seja selecionada toda a lista (-1), pega na verdade 1000
            if (PageSize == -1)
            {
                PageSize = 1000;
            }
            ViewBag.PageSize = PageSize;
            ViewBag.CurrentNumeroPaginas = NumeroPaginas;

            //Pagina corrente
            int PageNumber = (Page ?? 1);

            //DropDown de paginação
            int intNumeroPaginas = (NumeroPaginas ?? 5);
            ViewBag.NumeroPaginas = new SelectList(db.Paginacao, "valor", "nome", intNumeroPaginas);
            return View(lista.ToPagedList(PageNumber, PageSize));

        }

        // GET: Blocos/Details/5
        public ActionResult Details(int? id)
        {
            Localizacao();

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ArbitragemPeriodo arbitragemPeriodo = db.ArbitragemPeriodo.Find(id);
            if (arbitragemPeriodo == null)
            {
                return HttpNotFound();
            }

            IQueryable<Arbitragem> lista = db.Arbitragem.Where(x => x.ArbitragemPeriodoID == id).OrderBy(x => x.NivelAssociacao);
            if (lista == null)
            {
                return HttpNotFound();
            }
            ViewBag.Arbitragens = lista;

            ViewBag.Associacoes = db.Associacao;                                

            return View(arbitragemPeriodo);
        }

        // GET: Bloco/Create
        public ActionResult Create()
        {
            Localizacao();

            var lista = db.Associacao.Where(x => x.Nivel > 0).OrderBy(x => x.Nivel).ToList<Associacao>();

            ViewBag.Associacoes = lista;
            ViewBag.QuantidadeLinhas = lista.Count;

            var arbitragemPeriodo = db.ArbitragemPeriodo.OrderByDescending(x => x.DataInicio).FirstOrDefault<ArbitragemPeriodo>();

            if (arbitragemPeriodo != null)
            {
                ViewBag.DataInicio = arbitragemPeriodo.DataInicio.AddDays(7).ToString("dd/MM/yyy");
                ViewBag.DataFim = arbitragemPeriodo.DataFim.AddDays(7).ToString("dd/MM/yyy");
            }
            else
            {
                int dia = (int)Core.Helpers.App.DateTimeZion.DayOfWeek;
                ViewBag.DataInicio = Core.Helpers.App.DateTimeZion.AddDays(7-dia).ToString("dd/MM/yyy");
                ViewBag.DataFim = Core.Helpers.App.DateTimeZion.AddDays(13-dia).ToString("dd/MM/yyy");
            }

            return View();
        }

        // POST: Bloco/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,Nivel,Nome,DuracaoDias")] Associacao Associacao)
        //{
        //    Localizacao();

        //    List<string> msg = new List<string>();
        //    msg.Add(traducaoHelper["CAMPO_REQUERIDO"]);

        //    if (Associacao.Nivel == 0)
        //    {
        //        msg.Add(traducaoHelper["NIVEL"]);
        //    }
        //    if (string.IsNullOrEmpty(Associacao.Nome))
        //    {
        //        msg.Add(traducaoHelper["NOME"]);
        //    }
        //    if (Associacao.DuracaoDias == 0)
        //    {

Univer/Application/Adm/Views/Arbitragens/Create.cshtml
@model Core.Entities.Arbitragem

@{
    var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
    ViewBag.Title = traducaoHelper["CRIAR"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section pageStyles{
    @Styles.Render("~/Content/sweetAlert") 

    <style>
        .cel {
            padding: 0 !important;
            border: 0;
        }

            .cel input {
                padding: 0;
                border: 0;
                text-align: center !important;
                font-size: 16px !important;
            }
    </style>
}

@section head{
}

@section PageScripts{

    <script src="~/Content/global/plugins/Inputmask-4.x1111/dist/jquery.inputmask.bundle.js"></script>

    <script type="text/javascript">

        $(document).ready(function () {
            $('.percetual').inputmask('99,99 %', { numericInput: true, reverse: true });
        });


        function Gavar() {
            $.ajax({
                url: '@Url.Action("Gavar")',
                type: 'post',
                dataType: 'json',
                data: getDadosTabela(),
                //beforeSend: function (data) {
                //    Metronic.blockUI({
                //        animate: true,
                //        boxed: true,
                //        cenrerY: true
                //    });
                //},
                success: function (data) {
                    //Metronic.blockUI({
                    //    animate: false
                    //});
                    if (data == 'OK') {
                        swal('@traducaoHelper["SUCESSO"]', '@traducaoHelper["DADOS_SALVOS_SUCESSO"]', "success");
      
                        window.location = '@Url.Action("Index")';
                    }
                    else {
                        swal('@traducaoHelper["ERRO"]', data, "error");                    
                    }
                },
                error: function () {
                    //Metronic.blockUI({
                    //    animate: false
                    //});
                    swal('@traducaoHelper["ERRO"]', '@traducaoHelper["LOGIN_NAO_FOI_POSSIVEL_COMPLETAR_REQUISICAO"]', "error");
          
                }
            });
        };

        function getDadosTabela() {
            var strJson = '{' +
                '"dtInicio":"' + $("#dtInicio").text() + '",' +
                '"dtfim":"'    + $("#dtfim").text() + '",' +
                '"itens":[';
            for (var i = 1; i <= @ViewBag.QuantidadeLinhas; i++) {
                strJson += '{' +
                    '"nivelAssoc":"' + $("#nivelAssoc_" + i).text() + '",' +
                    '"percSeg":"' + $("#percSeg_" + i).val().replace(/_/g, '0').replace(',', '').replace('%', '').replace(' ', '') + '",' +
                    '"percTer":"' + $("#percTer_" + i).val().replace(/_/g, '0').replace(',', '').replace('%', '').replace(' ', '') + '",' +
                    '"percQua":"' + $("#percQua_" + i).val().replace(/_/g, '0').replace(',', '').replace('%', '').replace(' ', '') + '",' +
                    '"percQui":"' + $("#percQui_" + i).val().replace(/_/g, '0').replace(',', '').replace('%', '').replace(' ', '') + '",' +
                    '"percSex":"' + $("#percSex_" + i).val().replace(/_/g, '0').replace(',', '').replace('%', '').replace(' ', '') +
                '"}';

                if(i < @ViewBag.QuantidadeLinhas)
                {
                    strJson += ',';
                }
            }
            strJson += ']}';

            //console.log(strJson);

            return strJson;
        };

         function copiarLinha() {
             for (var i = 2; i <= @ViewBag.QuantidadeLinhas; i++) {
                 $("#percSeg_" + i).val($("#percSeg_1").val());
                 $("#percTer_" + i).val($("#percTer_1").val());
                 $("#percQua_" + i).val($("#percQua_1").val());
                 $("#percQui_" + i).val($("#percQui_1").val());
                 $("#percSex_" + i).val($("#percSex_1").val());
             };
        };

         function limparLinha() {
             for (var i = 1; i <= @ViewBag.QuantidadeLinhas; i++) {
                 $("#percSeg_" + i).val("");
                 $("#percTer_" + i).val("");
                 $("#percQua_" + i).val("");
                 $("#percQui_" + i).val("");
                 $("#percSex_" + i).val("");
             };
        };

    </script>
}

@section PageLevelScripts{

    @Scripts.Render("~/scripts/sweetAlert")
}

@section jQueryRead{
}


<div class="portlet box grey-gallery">

    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-plus"></i>@traducaoHelper["CRIAR"]
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"></a>
        </div>
        <div class="actions">
            <a href='javascript:limparLinha()' class="btn green-meadow">
                <i class="fa fa-eraser"></i> @traducaoHelper["LIMPAR"]
            </a>
            <a href='javascript:copiarLinha()' class="btn green-meadow">
                <i class="fa fa-copy"></i> @traducaoHelper["COPIAR"]
            </a>
            <label>&nbsp;</label>
        </div>
    </div>

    <div class="portlet-body form">
        <!-- Inicio FORM-->

        <div class="form-body">
            @using (Html.BeginForm())
            {
                @*@Html.AntiForgeryToken()*@
                <div class="form-horizontal">
                    <div class="row">
                        <div class="col-md-10"><h4>@traducaoHelper["ARBITRAGEM"] - <samp id="dtInicio">@ViewBag.DataInicio</samp> @traducaoHelper["ATE"] <samp id="dtfim">@ViewBag.DataFim</samp></h4></div>
                        <div class="col-md-2">@Html.ActionLink("Back to List", "Index", new { id = 0 }, new { @class = "Voltar pull-right", title = traducaoHelper["VOLTAR_PARA_A_LISTA"] })</div>
                    </div>
                    <hr />

                </div>
            }

            @if (ViewBag.Associacoes != null)
            {
                <div class="row">
                    <div class="col-md-12">
                        <div class="table-scrollable">
                            <table class="table table-striped table-bordered table-hover" id="tabelaConfig">
                                <thead>
                                    <tr>
                                        <th scope="col" width="25%" id="Associacao">@traducaoHelper["ASSOCIACAO"]</th>
                                        <th scope="col" width="15%" id="percent2">@traducaoHelper["SEGUNDA_FEIRA"]</th>
                                        <th scope="col" width="15%" id="percent3">@traducaoHelper["TERCA_FEIRA"]</th>
                                        <th scope="col" width="15%" id="percent4">@traducaoHelper["QUARTA_FEIRA"]</th>
                                        <th scope="col" width="15%" id="percent5">@traducaoHelper["QUINTA_FEIRA"]</th>
                                        <th scope="col" width="15%" id="percent6">@traducaoHelper["SEXTA_FEIRA"]</th>
                                    </tr>
                                </thead>
                                <tfoot>
                                    <tr>
                                        <th scope="col" width="25%" id="Associacao">@traducaoHelper["ASSOCIACAO"]</th>
                                        <th scope="col" width="15%" id="percent2">@traducaoHelper["SEGUNDA_FEIRA"]</th>
                                        <th scope="col" width="15%" id="percent3">@traducaoHelper["TERCA_FEIRA"]</th>
                                        <th scope="col" width="15%" id="percent4">@traducaoHelper["QUARTA_FEIRA"]</th>
                                        <th scope="col" width="15%" id="percent5">@traducaoHelper["QUINTA_FEIRA"]</th>
                                        <th scope="col" width="15%" id="percent6">@traducaoHelper["SEXTA_FEIRA"]</th>
                                    </tr>
                                </tfoot>
                                <tbody>
                                    @{
                                        int cont = 0;
                                        foreach (Core.Entities.Associacao item in ViewBag.Associacoes)
                                        {
                                            cont++;
                                            <tr>
                                                <td>
                                                    <div id="nivelAssoc_@cont" hidden>@item.Nivel</div>
                                                    @item.Nome
                                                </td>
                                                <td class="cel">
                                                    <input type="text" class="form-control percetual" id="percSeg_@cont" value="" />
                                                </td>
                                                <td class="cel">
                                                    <input type="text" class="form-control percetual" id="percTer_@cont" value="" />
                                                </td>
                                                <td class="cel">
                                                    <input type="text" class="form-control percetual" id="percQua_@cont" value="" />
                                                </td>
                                                <td class="cel">
                                                    <input type="text" class="form-control percetual" id="percQui_@cont" value="" />
                                                </td>
                                                <td class="cel">
                                                    <input type="text" class="form-control percetual" id="percSex_@cont" value="" />
                                                </td>
                                            </tr>
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <div class="form-group">
                        <div class="form-group">
                            <div class="col-md-12">
                                <input type="submit" value="@traducaoHelper["SALVAR"]" class="btn btn-success pull-right" onclick="Gavar();" />
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
        <!-- Fim FORM-->
    </div>
</div>

Univer/Application/Adm/Views/Arbitragens/Delete.cshtml
@model Core.Entities.ArbitragemPeriodo

@{
    var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
    ViewBag.Title = traducaoHelper["EXCLUIR"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="portlet box grey-gallery">

    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-eraser"></i>@traducaoHelper["EXCLUIR"]
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"></a>
        </div>
    </div>

    <div class="portlet-body form">
        <div class="form-body">
            <div class="row">
                <div class="col-md-10"><h4>@traducaoHelper["ARBITRAGEM"]</h4></div>
                <div class="col-md-2">@Html.ActionLink("Back to List", "Index", new { id = 0 }, new { @class = "Voltar pull-right", title = traducaoHelper["VOLTAR_PARA_A_LISTA"] })</div>
            </div>
            <h3 class="text-danger">@traducaoHelper["TEM_CERTEZA_QUE_DESEJA_EXLUIR_ESTE_ITEM"]</h3>
            <hr />
            <dl class="dl-horizontal">

                <dt>@traducaoHelper["DATA_INICIO"]</dt>
                <dd>
                    @Model.DataInicio.ToString("dd/MM/yyyy")
                </dd>
                <dt>@traducaoHelper["DATA_FIM"]</dt>
                <dd>
                    @Model.DataFim.ToString("dd/MM/yyyy")
                </dd>

            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <input type="submit" value="@traducaoHelper["EXCLUIR"]" class="btn btn-danger" id="confirm_button" />
                </div>
            }
        </div>
    </div>
</div>

Univer/Application/Adm/Views/Arbitragens/Index.cshtml
@model PagedList.IPagedList<Core.Entities.ArbitragemPeriodo>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
}

<div class="portlet box grey-gallery">

    <div class="portlet-title">
        <div class="caption"><i class="fa fa-reorder"></i> @traducaoHelper["ARBITRAGEM"] </div>
        <div class="tools">
            <a href="javascript:;" class="collapse" title="@traducaoHelper["FECHAR"]" />
            <a href='@Url.Action("Reload", "Arbitragens")' class="atualizar" title="@traducaoHelper["RELER"]" />
        </div>
        <div class="actions">
            <a href='@Url.Action("Create", "Arbitragens", new {@id = 0})' class="btn green-meadow">
                <i class="fa fa-plus"></i> @traducaoHelper["NOVO"]
            </a>
            <label>&nbsp;</label>
        </div>
    </div>

    <div class="portlet-body">
        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <div class="input-group">
                            @using (Html.BeginForm("Index", "Arbitragens", FormMethod.Get))
                            {
                                @Html.DropDownList("NumeroPaginas", null, htmlAttributes: new { @class = "form-control input-small input-inline marginB05" })
                                <input class="btn purple form-control input-small input-inline fontPlaceHolderIcon" id="Atualizar" name="Atualizar" value="&#xf021; @traducaoHelper["ATUALIZAR"]" type="submit" />
                            }
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    @using (Html.BeginForm("Index", "Arbitragens", FormMethod.Get))
                    {
                        <div class="form-group pull-right">
                            <div class="input-group">
                                @Html.TextBox("ProcuraData", ViewBag.CurrentProcuraData as string, new { @class = "form-control input-small input-inline fontPlaceHolderIcon marginB05", @placeholder = traducaoHelper["DATA"], @type = "date" })
                                <input class="btn blue-madison form-control input-small input-inline fontPlaceHolderIcon" id="Procura" name="Procura" value="&#xf002; @traducaoHelper["PROCURAR"]" type="submit" />
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="row">
                <div class=" col-md-10">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, SortOrder = ViewBag.CurrentSort, CurrentProcuraData = ViewBag.CurrentProcuraData, CurrentProcuraValor = ViewBag.CurrentProcuraValor, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize }))
                </div>
                <div class=" col-md-2">
                    <label class="pull-right">@traducaoHelper["PAG"] @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @traducaoHelper["DE"] @Model.PageCount &nbsp;</label>
                </div>
            </div>
        </div>

        <div class="table-scrollable">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th scope="col" style="min-width:80px; width:80px;">&nbsp;@traducaoHelper["ACOES"]&nbsp;</th>
                        <th scope="col">
                            @Html.ActionLink(traducaoHelper["DATA_INICIO"], "Index", new { SortOrder = ViewBag.NameSortParm, CurrentProcuraData = ViewBag.CurrentProcuraData, CurrentProcuraValor = ViewBag.CurrentProcuraValor, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize })
                            @switch ((string)ViewBag.CurrentSort.ToString())
                            {
                                case "name":
                                    {<i class="fa fa-chevron-down"></i>}
                                    break;
                                case "name_desc":
                                    {<i class="fa fa-chevron-up"></i>}
                                    break;
                            }
                        </th>
                        <th scope="col">@traducaoHelper["DATA_FIM"]</th>         
                    </tr>
                </thead>
                <tfoot>
                    <tr>
                        <th scope="col" style="min-width:80px; width:80px;">&nbsp;@traducaoHelper["ACOES"]&nbsp;</th>
                        <th scope="col" style="padding:8px;">
                            @Html.ActionLink(traducaoHelper["DATA_INICIO"], "Index", new { SortOrder = ViewBag.NameSortParm, CurrentProcuraData = ViewBag.CurrentProcuraData, CurrentProcuraValor = ViewBag.CurrentProcuraValor, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize })
                            @switch ((string)ViewBag.CurrentSort.ToString())
                            {
                                case "name":
                                    {<i class="fa fa-chevron-down"></i>}
                                    break;
                                case "name_desc":
                                    {<i class="fa fa-chevron-up"></i>}
                                    break;
                            }
                        </th>
                        <th scope="col" style="padding:8px;">@traducaoHelper["DATA_FIM"]</th>                   
                    </tr>
                </tfoot>

                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @if (item.DataFim > Core.Helpers.App.DateTimeZion)
                                {
                                    @Html.ActionLink("Edit", "Edit", new { id = item.ID }, new { @class = "gridEdit", title = traducaoHelper["EDITAR"] })
                                }
                                @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "gridDetail", title = traducaoHelper["DETALHES"] })
                                @if (item.DataInicio > Core.Helpers.App.DateTimeZion)
                                {
                                    @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "gridDelete", title = traducaoHelper["EXCLUIR"] })
                                }
                                </td>
                            <td>
                                @item.DataInicio.ToString("dd/MM/yyyy")
                            </td>
                            <td>
                                @item.DataFim.ToString("dd/MM/yyyy")
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <div class="row">
            <div class="border-gridFooter">
                <div class="col-md-10">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, SortOrder = ViewBag.CurrentSort, CurrentProcuraData = ViewBag.CurrentProcuraData, CurrentProcuraValor = ViewBag.CurrentProcuraValor, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize }))
                </div>
                <div class="col-md-2">
                    <label class="pull-right">@traducaoHelper["PAG"]  @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @traducaoHelper["DE"]  @Model.PageCount &nbsp;</label>
                </div>
            </div>
        </div>
    </div>

</div>