Univer/Application/Adm/Controllers/DadosBasicos/PaginacoesController.cs
#region Bibliotecas

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.IO;

//Identyty
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;

//Entity
using Core.Entities;

//Models Local
using Sistema.Models;

//Lista
using PagedList;
using Helpers;

//Excel
using ClosedXML.Excel;
using cpUtilities;
using System.Threading;
using System.Data.Entity.Validation;
using System.Data.SqlClient;

#endregion

namespace Sistema.Controllers
{
   [Authorize(Roles = "Master, perfilAdministrador")]
   public class PaginacoesController : Controller
   {
      #region Variaveis

      private YLEVELEntities db = new YLEVELEntities();

      #endregion

      #region Mensagem

      public void Mensagem(string titulo, string[] mensagem, string tipo)
      {
         Session["strPoppup"] = tipo;
         Session["strMensagem"] = mensagem;
         Session["strTitulo"] = titulo;
      }

      public void obtemMensagem()
      {
         string strErr = "NOOK";
         string strAle = "NOOK";
         string strMsg = "NOOK";
         string strTipo = "";

         if (Session["strPoppup"] != null)
         {
            strTipo = Session["strPoppup"].ToString();
         }

         switch (strTipo)
         {
            case "err":
               strErr = "OK";
               break;
            case "ale":
               strAle = "OK";
               break;
            case "msg":
               strMsg = "OK";
               break;
         }

         ViewBag.PopupErr = strErr;
         ViewBag.PopupMsg = strMsg;
         ViewBag.PopupAlert = strAle;

         ViewBag.PopupTitle = Session["strTitulo"];
         ViewBag.PopupMessage = Session["strMensagem"];

         Session["strPoppup"] = "NOOK";
         Session["strTitulo"] = "";
         Session["strMensagem"] = "";
      }
      #endregion

      #region Helpers

      private void Localizacao()
      {
         Core.Entities.Idioma idioma = Local.UsuarioIdioma;

         ViewBag.TraducaoHelper = new Core.Helpers.TraducaoHelper(idioma);
         var culture = new System.Globalization.CultureInfo("en-US");  //var culture = new System.Globalization.CultureInfo(idioma.Sigla);
         Thread.CurrentThread.CurrentCulture = culture;
         Thread.CurrentThread.CurrentUICulture = culture;
      }

      #endregion

      #region Actions
      // GET: Paginacao
      public ActionResult Index(string SortOrder, string CurrentProcuraNome, string ProcuraNome, int? NumeroPaginas, int? Page)
      {
         Localizacao();

         //Verifica se a msg em popup para ser exibido na view
         obtemMensagem();

         //Persistencia dos paramentros da tela
         Funcoes objFuncoes = new Funcoes(this.HttpContext);
         objFuncoes.Persistencia(ref SortOrder, ref CurrentProcuraNome, ref ProcuraNome, ref NumeroPaginas, ref Page, "Paginacao");
         objFuncoes = null;

         //List
         if (String.IsNullOrEmpty(SortOrder))
         {
            ViewBag.CurrentSort = "nome";
         }
         else
         {
            ViewBag.CurrentSort = SortOrder;
         }

         if (!(ProcuraNome != null))
         {
            if (ProcuraNome == null)
            {
               ProcuraNome = CurrentProcuraNome;
            }
         }

         ViewBag.CurrentProcuraNome = ProcuraNome;

         IQueryable<Paginacao> lista = null;
         lista = db.Paginacao;
         if (!String.IsNullOrEmpty(ProcuraNome))
         {
            lista = lista.Where(s => s.nome.Contains(ProcuraNome));
         }

         switch (SortOrder)
         {
            case "nome_desc":
               ViewBag.FirstSortParm = "nome";
               ViewBag.SecondSortParm = "nome";
               lista = lista.OrderByDescending(x => x.nome);
               break;
            case "nome":
               ViewBag.FirstSortParm = "nome";
               ViewBag.SecondSortParm = "Nome";
               lista = lista.OrderBy(x => x.nome);
               break;
            default:  // Name ascending 
               ViewBag.FirstSortParm = "nome_desc";
               ViewBag.SecondSortParm = "nome";
               lista = lista.OrderBy(x => x.nome);
               break;
         }

         //Numero de linhas por Pagina
         int PageSize = (NumeroPaginas ?? 5);

         //Caso seja selecionada toda a lista (-1), pega na verdade 1000
         if (PageSize == -1)
         {
            PageSize = 1000;
         }
         ViewBag.PageSize = PageSize;
         ViewBag.CurrentNumeroPaginas = NumeroPaginas;

         //Pagina corrente
         int PageNumber = (Page ?? 1);

         //DropDown de paginação
         int intNumeroPaginas = (NumeroPaginas ?? 5);
         ViewBag.NumeroPaginas = new SelectList(db.Paginacao, "valor", "nome", intNumeroPaginas);
         return View(lista.ToPagedList(PageNumber, PageSize));

      }

      // GET: Paginacao/Details/5
      public ActionResult Details(int? id)
      {
         Localizacao();

         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Paginacao Paginacao = db.Paginacao.Find(id);
         if (Paginacao == null)
         {
            return HttpNotFound();
         }
         return View(Paginacao);
      }

      // GET: Bloco/Create
      public ActionResult Create()
      {
         Localizacao();

         return View();
      }

      // POST: Bloco/Create
      // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
      
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Create([Bind(Include = "ID,atualizacao, nome, valor")] Paginacao Paginacao)
      {
         Localizacao();

         if (ModelState.IsValid)
         {
            db.Paginacao.Add(Paginacao);
            db.SaveChanges();
            return RedirectToAction("Index");
         }

         return View(Paginacao);
      }

      // GET: Bloco/Edit/5
      public ActionResult Edit(int? id)
      {
         Localizacao();

         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Paginacao Paginacao = db.Paginacao.Find(id);
         if (Paginacao == null)
         {
            return HttpNotFound();
         }
         return View(Paginacao);
      }

      // POST: Bloco/Edit/5
      // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
      
      [HttpPost]
      [ValidateAntiForgeryToken]
      public ActionResult Edit([Bind(Include = "ID,atualizacao, nome, valor")] Paginacao Paginacao)
      {
         Localizacao();

         if (ModelState.IsValid)
         {
            db.Entry(Paginacao).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
         }
         return View(Paginacao);
      }

      // GET: Bloco/Delete/5
      public ActionResult Delete(int? id)
      {
         Localizacao();

         if (id == null)
         {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
         }
         Paginacao Paginacao = db.Paginacao.Find(id);
         if (Paginacao == null)
         {
            return HttpNotFound();
         }
         return View(Paginacao);
      }

      // POST: Bloco/Delete/5
      [HttpPost, ActionName("Delete")]
      [ValidateAntiForgeryToken]
      public ActionResult DeleteConfirmed(int id)
      {
         Localizacao();

         Paginacao Paginacao = db.Paginacao.Find(id);
         db.Paginacao.Remove(Paginacao);
         db.SaveChanges();
         return RedirectToAction("Index");
      }

      public ActionResult Reload()
      {
         Localizacao();

         //Persistencia dos paramentros da tela
         Funcoes objFuncoes = new Funcoes(this.HttpContext);
         objFuncoes.LimparPersistencia();
         objFuncoes = null;
         return RedirectToAction("Index");
      }

      protected override void Dispose(bool disposing)
      {
         Localizacao();

         if (disposing)
         {
            db.Dispose();
         }
         base.Dispose(disposing);
      }

      #endregion

   }
}

Univer/Application/Adm/Views/Paginacoes/Create.cshtml
@model Core.Entities.Paginacao

@{
   var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
   ViewBag.Title = traducaoHelper["CRIAR"];
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="portlet box grey-gallery">
   <div class="portlet-title">
      <div class="caption">
         <i class="fa fa-plus"></i>@traducaoHelper["CRIAR"]
      </div>
      <div class="tools">
         <a href="javascript:;" class="collapse"></a>
      </div>
   </div>
   <div class="portlet-body form">
      <!-- Inicio FORM-->
      @using (Html.BeginForm())
      {
         @Html.AntiForgeryToken()
         <div class="form-body">
            <div class="form-horizontal">
               <div class="row">
                  <div class="col-md-10"><h4> @traducaoHelper["PAGINACAO"] </h4></div>
                  <div class="col-md-2">@Html.ActionLink("Back to List", "Index", new { id = 0 }, new { @class = "Voltar pull-right", title = traducaoHelper["VOLTAR_PARA_A_LISTA"] })</div>
               </div>
               <hr />
               @Html.ValidationSummary(true, "", new { @class = "text-danger" })
               <div class="form-group">
                  <label class="control-label col-md-2" for="atualizacao">@traducaoHelper["NOME"]</label>
                  <div class="col-md-10">
                     @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                     @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
                  </div>
               </div>

               <div class="form-group">
                  <label class="control-label col-md-2" for="atualizacao">@traducaoHelper["VALOR"]</label>
                  <div class="col-md-10">
                     @Html.EditorFor(model => model.valor, new { htmlAttributes = new { @class = "form-control" } })
                     @Html.ValidationMessageFor(model => model.valor, "", new { @class = "text-danger" })
                  </div>
               </div>
               <div class="form-group">
                  <label class="control-label col-md-2" for="atualizacao">@traducaoHelper["ATUALIZACAO"]</label>
                  <div class="col-md-10">
                     @Html.EditorFor(model => model.atualizacao, new { htmlAttributes = new { @class = "form-control" } })
                     @Html.ValidationMessageFor(model => model.atualizacao, "", new { @class = "text-danger" })
                  </div>
               </div>
               <div class="form-group">
                  <div class="col-md-offset-2 col-md-10">
                     <input type="submit" value="@traducaoHelper["CRIAR"]" class="btn btn-success" />
                  </div>
               </div>
            </div>
         </div>
      }
      <!-- Fim FORM-->
   </div>

</div>

Univer/Application/Adm/Views/Paginacoes/Delete.cshtml
@model Core.Entities.Paginacao
@{
   var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
   ViewBag.Title = ViewBag.Title = traducaoHelper["EXCLUIR"];
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="portlet box grey-gallery">

   <div class="portlet-title">
      <div class="caption">
         <i class="fa fa-eraser"></i>@traducaoHelper["EXCLUIR"]
      </div>
      <div class="tools">
         <a href="javascript:;" class="collapse"></a>
      </div>
   </div>

   <div class="portlet-body form">
      <div class="form-body">
         <div class="row">
            <div class="col-md-10"><h4>@traducaoHelper["PAGINACAO"]</h4></div>
            <div class="col-md-2">@Html.ActionLink("Back to List", "Index", new { id = 0 }, new { @class = "Voltar pull-right", title = traducaoHelper["VOLTAR_PARA_A_LISTA"] })</div>
         </div>
         <h3 class="text-danger">@traducaoHelper["TEM_CERTEZA_QUE_DESEJA_EXLUIR_ESTE_ITEM"]</h3>
         <hr />
         <dl class="dl-horizontal">
            <dt>@traducaoHelper["NOME"]</dt>
            <dd>
               @Html.DisplayFor(model => model.nome)
            </dd>
            <dt>@traducaoHelper["VALOR"]</dt>
            <dd>
               @Html.DisplayFor(model => model.valor)
            </dd>
            <dt>@traducaoHelper["ATUALIZACAO"]</dt>
            <dd>
               @Html.DisplayFor(model => model.atualizacao)
            </dd>
            <dd>
            </dd>
         </dl>

         @using (Html.BeginForm())
         {
            @Html.AntiForgeryToken()
            <div class="form-actions no-color">
               <input type="submit" value="@traducaoHelper["EXCLUIR"]" class="btn btn-danger" id="confirm_button" />
            </div>
         }
      </div>
   </div>
</div>

Univer/Application/Adm/Views/Paginacoes/Details.cshtml
@model Core.Entities.Paginacao

@{
   var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
   ViewBag.Title = traducaoHelper["DETALHES"];
   Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="portlet box grey-gallery">

   <div class="portlet-title">
      <div class="caption">
         <i class="fa fa-book "></i>@traducaoHelper["DETALHES"]
      </div>
      <div class="tools">
         <a href="javascript:;" class="collapse"></a>
      </div>
   </div>

   <div class="portlet-body form">

      <div class="form-body">
         <div class="row">
            <div class="col-md-10"><h4>@traducaoHelper["PAGINACAO"]</h4></div>
            <div class="col-md-2">
               @Html.ActionLink("Back to List", "Index", new { id = 0 }, new { @class = "Voltar pull-right", title = traducaoHelper["VOLTAR_PARA_A_LISTA"] })
               @Html.ActionLink("Edit", "Edit", new { id = Model.id }, new { @class = "Editar pull-right", title = traducaoHelper["EDITAR"] })
            </div>
         </div>
         <hr />
         <dl class="dl-horizontal">
            <dt>@traducaoHelper["NOME"]</dt>
            <dd>
               @Html.DisplayFor(model => model.nome)
            </dd>
            <dt>@traducaoHelper["VALOR"]</dt>
            <dd>
               @Html.DisplayFor(model => model.valor)
            </dd>
            <dt>@traducaoHelper["ATUALIZACAO"]</dt>
            <dd>
               @Html.DisplayFor(model => model.atualizacao)
            </dd>
            <dd>
            </dd>
         </dl>
      </div>
   </div>
</div>

Univer/Application/Adm/Views/Paginacoes/Edit.cshtml
@model Core.Entities.Paginacao

@{
   var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
   ViewBag.Title = traducaoHelper["EDITAR"];
   Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="portlet box grey-gallery">

   <div class="portlet-title">
      <div class="caption">
         <i class="fa fa-pencil"></i>@traducaoHelper["EDITAR"]
      </div>
      <div class="tools">
         <a href="javascript:;" class="collapse"></a>
      </div>
   </div>

   <div class="portlet-body form">
      <!-- BEGIN FORM-->
      @using (Html.BeginForm())
      {
         @Html.AntiForgeryToken()
         <div class="form-body">
            <div class="form-horizontal">
               <div class="row">
                  <div class="col-md-10"><h4>@traducaoHelper["PAGINACAO"]</h4></div>
                  <div class="col-md-2">@Html.ActionLink("Back to List", "Index", new { id = 0 }, new { @class = "Voltar pull-right", title = traducaoHelper["VOLTAR_PARA_A_LISTA"] })</div>
               </div>
               <hr />
               @Html.ValidationSummary(true, "", new { @class = "text-danger" })
               @Html.HiddenFor(model => model.id)

               <div class="form-group">
                  <label class="control-label col-md-2" for="atualizacao">@traducaoHelper["NOME"]</label>
                  <div class="col-md-10">
                     @Html.EditorFor(model => model.nome, new { htmlAttributes = new { @class = "form-control" } })
                     @Html.ValidationMessageFor(model => model.nome, "", new { @class = "text-danger" })
                  </div>
               </div>

               <div class="form-group">
                  <label class="control-label col-md-2" for="atualizacao">@traducaoHelper["VALOR"]</label>
                  <div class="col-md-10">
                     @Html.EditorFor(model => model.valor, new { htmlAttributes = new { @class = "form-control" } })
                     @Html.ValidationMessageFor(model => model.valor, "", new { @class = "text-danger" })
                  </div>
               </div>
               <div class="form-group">
                  <label class="control-label col-md-2" for="atualizacao">@traducaoHelper["ATUALIZACAO"]</label>
                  <div class="col-md-10">
                     @Html.EditorFor(model => model.atualizacao, new { htmlAttributes = new { @class = "form-control" } })
                     @Html.ValidationMessageFor(model => model.atualizacao, "", new { @class = "text-danger" })
                  </div>
               </div>
               <div class="form-group">
                  <div class="col-md-offset-2 col-md-10">
                     <input type="submit" value="@traducaoHelper["EDITAR"]" class="btn green-haze" />
                  </div>
               </div>
            </div>
         </div>
      }
   </div>

</div>

Univer/Application/Adm/Views/Paginacoes/Index.cshtml
@model PagedList.IPagedList<Core.Entities.Paginacao>
@using PagedList.Mvc;

@{
   ViewBag.Title = "Index";
   Layout = "~/Views/Shared/_Layout.cshtml";
   var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
}

<div class="portlet box grey-gallery">

   <div class="portlet-title">
      <div class="caption"><i class="fa fa-reorder"></i> @traducaoHelper["PAGINACAO"]</div>
      <div class="tools">
         <a href="javascript:;" class="collapse" title="@traducaoHelper["FECHAR"]" />
         <a href='@Url.Action("Reload", "Paginacoes")' class="atualizar" title="@traducaoHelper["RELER"]" />
      </div>
      <div class="actions">
         <a href='@Url.Action("Create", "Paginacoes", new {@id = 0})' class="btn green-meadow">
            <i class="fa fa-plus"></i> @traducaoHelper["NOVO"]
         </a>
         <a href='@Url.Action("Excel", "Paginacoes")' class="btn btn-sm yellow-casablanca">
            <i class="fa fa-file-excel-o"></i> Excel
         </a>
         <label>&nbsp;</label>
      </div>
   </div>

   <div class="portlet-body">

      <div class="table-toolbar">
         <div class="row">
            <div class="col-md-4">
               <div class="form-group">
                  <div class="input-group">
                     @using (Html.BeginForm("Index", "Paginacoes", FormMethod.Get))
                     {
                        @Html.DropDownList("NumeroPaginas", null, htmlAttributes: new { @class = "form-control input-small input-inline marginB05" })
                        <input class="btn purple form-control input-small input-inline fontPlaceHolderIcon" id="Atualizar" name="Atualizar" value="&#xf021; @traducaoHelper["ATUALIZAR"]" type="submit" />
                     }
                  </div>
               </div>
            </div>
            <div class="col-md-8">
               @using (Html.BeginForm("Index", "Paginacoes", FormMethod.Get))
               {
                  <div class="form-group pull-right">
                     <div class="input-group">
                        @Html.TextBox("Procuranome", ViewBag.CurrentProcuranome as string, new { @class = "form-control input-small input-inline fontPlaceHolderIcon marginB05", @placeholder = traducaoHelper["NOME"] })
                        <input class="btn blue-madison form-control input-small input-inline fontPlaceHolderIcon" id="Procura" name="Procura" value="&#xf002; @traducaoHelper["PROCURAR"]" type="submit" />
                     </div>
                  </div>
               }
            </div>
         </div>
         <div class="row">
            <div class="col-md-10">
               @Html.PagedListPager(Model, page => Url.Action("Index", new { page, SortOrder = ViewBag.CurrentSort, CurrentProcuranome = ViewBag.CurrentProcuranome, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize }))
            </div>
            <div class="col-md-2">
               <label class="pull-right">@traducaoHelper["PAG"] @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @traducaoHelper["DE"] @Model.PageCount &nbsp;</label>
            </div>
         </div>
      </div>

      <div class="table-scrollable">
         <table class="table table-striped table-bordered table-hover">
            <thead>
               <tr>
                  <th scope="col" style="min-width:80px; width:80px;">&nbsp;@traducaoHelper["ACOES"]&nbsp;</th>
                  <th scope="col">
                     @Html.ActionLink(traducaoHelper["NOME"], "Index", new { SortOrder = ViewBag.FirstSortParm, CurrentProcuranome = ViewBag.CurrentProcuranome, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize })
                     @switch ((string)ViewBag.CurrentSort.ToString())
                     {
                        case "nome":
                           {<i class="fa fa-chevron-down"></i>}
                           break;
                        case "nome_desc":
                           {<i class="fa fa-chevron-up"></i>}
                           break;
                     }
                  </th>
                  <th scope="col">@traducaoHelper["VALOR"]</th>
                  <th scope="col">@traducaoHelper["ATUALIZACAO"]</th>
               </tr>
            </thead>
            <tfoot>
               <tr>
                  <th scope="col" style="min-width:80px; width:80px;">&nbsp;@traducaoHelper["ACOES"]&nbsp;</th>
                  <th scope="col">
                     @Html.ActionLink(traducaoHelper["NOME"], "Index", new { SortOrder = ViewBag.FirstSortParm, CurrentProcuranome = ViewBag.CurrentProcuranome, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize })
                     @switch ((string)ViewBag.CurrentSort.ToString())
                     {
                        case "nome":
                           {<i class="fa fa-chevron-down"></i>}
                           break;
                        case "nome_desc":
                           {<i class="fa fa-chevron-up"></i>}
                           break;
                     }
                  </th>
                  <th scope="col">@traducaoHelper["VALOR"]</th>
                  <th scope="col">@traducaoHelper["ATUALIZACAO"]</th>
               </tr>
            </tfoot>
            <tbody>
               @foreach (var item in Model)
               {
                  <tr>
                     <td>
                        @Html.ActionLink("Edit", "Edit", new { id = item.id }, new { @class = "gridEdit", title = traducaoHelper["EDITAR"] })
                        @Html.ActionLink("Details", "Details", new { id = item.id }, new { @class = "gridDetail", title = traducaoHelper["DETALHES"] })
                        @Html.ActionLink("Delete", "Delete", new { id = item.id }, new { @class = "gridDelete", title = traducaoHelper["EXCLUIR"] })
                     </td>
                     <td>
                        @Html.DisplayFor(modelItem => item.nome)
                     </td>
                     <td>
                        @Html.DisplayFor(modelItem => item.valor)
                     </td>
                     <td>
                        @Html.DisplayFor(modelItem => item.atualizacao)
                     </td>
                  </tr>
               }
            </tbody>
         </table>
      </div>

      <div class="row">
         <div class="border-gridFooter">
            <div class="col-md-10">
               @Html.PagedListPager(Model, page => Url.Action("Index", new { page, SortOrder = ViewBag.CurrentSort, CurrentProcuranome = ViewBag.CurrentProcuranome, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize }))
            </div>
            <div class="col-md-2">
               <label class="pull-right">@traducaoHelper["PAG"]  @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @traducaoHelper["DE"]  @Model.PageCount &nbsp;</label>
            </div>
         </div>
      </div>

   </div>

</div>