Univer/Application/Adm/Controllers/Usuarios/AvisosController.cs
#region Bibliotecas

using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.IO;

//Identyty
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNet.Identity.EntityFramework;

//Entity
using Core.Entities;
using Core.Repositories.Usuario;

//Models Local
using Sistema.Models;

//Lista
using PagedList;
using Helpers;

//Excel
using ClosedXML.Excel;
using cpUtilities;
using System.Threading;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Web.Script.Serialization;

#endregion

namespace Sistema.Controllers
{
    public class AvisosController : Controller
    {
        #region Variaveis
        
        private DbContext _context;

        #endregion

        #region Core

        private Core.Helpers.TraducaoHelper traducaoHelper;

        private UsuarioRepository usuarioRepository;

        public AvisosController(DbContext context)
        {
            usuarioRepository = new UsuarioRepository(context);
            Localizacao();
            _context = context;
        }

        private YLEVELEntities db = new YLEVELEntities();

        #endregion

        #region Mensagem

        public void Mensagem(string titulo, string[] mensagem, string tipo)
        {
            Session["strPoppup"] = tipo;
            Session["strMensagem"] = mensagem;
            Session["strTitulo"] = titulo;
        }

        public void obtemMensagem()
        {
            string strErr = "NOOK";
            string strAle = "NOOK";
            string strMsg = "NOOK";
            string strTipo = "";

            if (Session["strPoppup"] != null)
            {
                strTipo = Session["strPoppup"].ToString();
            }

            switch (strTipo)
            {
                case "err":
                    strErr = "OK";
                    break;
                case "ale":
                    strAle = "OK";
                    break;
                case "msg":
                    strMsg = "OK";
                    break;
            }

            ViewBag.PopupErr = strErr;
            ViewBag.PopupMsg = strMsg;
            ViewBag.PopupAlert = strAle;

            ViewBag.PopupTitle = Session["strTitulo"];
            ViewBag.PopupMessage = Session["strMensagem"];

            Session["strPoppup"] = "NOOK";
            Session["strTitulo"] = "";
            Session["strMensagem"] = "";
        }
        #endregion

        #region Helpers

        private void Localizacao()
        {
            Core.Entities.Idioma idioma = Local.UsuarioIdioma;

            ViewBag.TraducaoHelper = new Core.Helpers.TraducaoHelper(idioma);
            traducaoHelper = new Core.Helpers.TraducaoHelper(idioma);
            var culture = new System.Globalization.CultureInfo("en-US");  //var culture = new System.Globalization.CultureInfo("en-US");  //var culture = new System.Globalization.CultureInfo(idioma.Sigla);
            Thread.CurrentThread.CurrentCulture = culture;
            Thread.CurrentThread.CurrentUICulture = culture;
        }

        #endregion

        #region Actions

        public ActionResult Index(string SortOrder, string CurrentProcuraTitulo, string ProcuraTitulo, int? NumeroPaginas, int? Page)
        {
            Localizacao();

            //Verifica se a msg em popup para ser exibido na view
            obtemMensagem();

            //Persistencia dos paramentros da tela
            Funcoes objFuncoes = new Funcoes(this.HttpContext);
            objFuncoes.Persistencia(ref SortOrder, ref CurrentProcuraTitulo, ref ProcuraTitulo, ref NumeroPaginas, ref Page, "Aviso");
            objFuncoes = null;

            //List
            if (String.IsNullOrEmpty(SortOrder))
            {
                ViewBag.CurrentSort = "Titulo";
            }
            else
            {
                ViewBag.CurrentSort = SortOrder;
            }

            if (!(ProcuraTitulo != null))
            {
                if (ProcuraTitulo == null)
                {
                    ProcuraTitulo = CurrentProcuraTitulo;
                }
            }

            ViewBag.CurrentProcuraTitulo = ProcuraTitulo;

            IQueryable<Aviso> lista = null;
            lista = db.Aviso;
            if (!String.IsNullOrEmpty(ProcuraTitulo))
            {
                lista = lista.Where(s => s.Titulo.Contains(ProcuraTitulo));
            }

            switch (SortOrder)
            {
                case "Titulo_desc":
                    ViewBag.NameSortParm = "Titulo";
                    lista = lista.OrderByDescending(s => s.Titulo);
                    break;
                case "Titulo":
                    ViewBag.NameSortParm = "Titulo_desc";

                    lista = lista.OrderBy(s => s.Titulo);
                    break;
                default:  // Name ascending 
                    ViewBag.NameSortParm = "Titulo_desc";
                    lista = lista.OrderBy(s => s.Titulo);
                    break;
            }

            //Numero de linhas por Pagina
            int PageSize = (NumeroPaginas ?? 5);

            //Caso seja selecionada toda a lista (-1), pega na verdade 1000
            if (PageSize == -1)
            {
                PageSize = 1000;
            }
            ViewBag.PageSize = PageSize;
            ViewBag.CurrentNumeroPaginas = NumeroPaginas;

            //Pagina corrente
            int PageNumber = (Page ?? 1);

            //DropDown de paginação
            int intNumeroPaginas = (NumeroPaginas ?? 5);
            ViewBag.NumeroPaginas = new SelectList(db.Paginacao, "valor", "nome", intNumeroPaginas);
            return View(lista.ToPagedList(PageNumber, PageSize));
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aviso aviso = db.Aviso.Find(id.Value);
            if (aviso == null)
            {
                return HttpNotFound();
            }

            SetViewBagComUsuariosJson(aviso);


            return View(aviso);
        }

        private void SetViewBag()
        {
            ViewBag.TipoID = new SelectList(db.AvisoTipo.Where(x => x.ID > 1), "ID", "Nome");
            ViewBag.IdiomaID = new SelectList(db.Idiomas, "ID", "Nome");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind] Aviso aviso)
        {
            // (Include = "ID,Titulo,Texto,TipoID,UsuarioID,IdiomaID,Login,Nome,Email,Atualizacao,DataDivulgacao,Urgente")
            if (ModelState.IsValid)
            {
                try
                {
                    aviso.Atualizacao = Core.Helpers.App.DateTimeZion;

                    if (aviso.ID.Equals(0))
                    {
                        db.Aviso.Add(aviso);
                    }
                    else
                    {
                        db.Entry(aviso).State = EntityState.Modified;
                    }

                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                catch (DbEntityValidationException dbEx)
                {
                    string strRetErro = "";
                    foreach (var validationErrors in dbEx.EntityValidationErrors)
                    {
                        foreach (var validationError in validationErrors.ValidationErrors)
                        {
                            strRetErro += validationError.PropertyName + ": " + validationError.ErrorMessage + " ";
                        }
                    }
                    string[] strMensagem = new string[] { strRetErro };
                    Mensagem(" " + traducaoHelper["ERRO"] + " ", strMensagem, "err");
                }
                catch (Exception ex)
                {
                    string[] strMensagem = new string[] { ex.Message };
                    Mensagem(" " + traducaoHelper["ERRO"] + " ", strMensagem, "err");
                }
            }

            obtemMensagem();

            ViewBag.TipoID = new SelectList(db.AvisoTipo.Where(x => x.ID > 1), "ID", "Nome");
            ViewBag.IdiomaID = new SelectList(db.Idiomas, "ID", "Nome");

            return View(aviso);
        }

        public ActionResult Create(int? id)
        {
            this.SetViewBag();

            Aviso aviso = new Aviso();

            if (id.HasValue)
            {
                aviso = db.Aviso.FirstOrDefault(f => f.ID == id.Value);

                if (aviso == null)
                {
                    return HttpNotFound();
                }

                SetViewBagComUsuariosJson(aviso);

            }

            return View("create", aviso);
        }

        private void SetViewBagComUsuariosJson(Core.Entities.Aviso aviso)
        {
            var usuariosIDs = new List<ItemViewModel>();

            if (aviso.UsuarioIDs != null)
            {
                var ids = aviso.UsuarioIDs.Split(',');

                foreach (var item in ids.Where(w => !string.IsNullOrEmpty(w)))
                {
                    var usuario = db.Usuarios.Find(int.Parse(item));

                    usuariosIDs.Add(new ItemViewModel { id = usuario.ID, Name = usuario.Login });
                }
            }

            if (usuariosIDs.Any())
            {
                ViewBag.UsuariosIDs = usuariosIDs;
                ViewBag.UsuariosJson = new JavaScriptSerializer().Serialize(usuariosIDs);
            }
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Aviso aviso = db.Aviso.Find(id);
            if (aviso == null)
            {

Univer/Application/Adm/Views/Avisos/Delete.cshtml
@model Core.Entities.Aviso
@{
    var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
    ViewBag.Title = ViewBag.Title = traducaoHelper["EXCLUIR"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="portlet box grey-gallery">

    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-eraser"></i>@traducaoHelper["EXCLUIR"]
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"></a>
        </div>
    </div>

    <div class="portlet-body form">
        <div class="form-body">
            <div class="row">
                <div class="col-md-10"><h4>@traducaoHelper["ATIVOS"]</h4></div>
                <div class="col-md-2">@Html.ActionLink("Back to List", "Index", new { id = 0 }, new { @class = "Voltar pull-right", title = traducaoHelper["VOLTAR_PARA_A_LISTA"] })</div>
            </div>
            <h3 class="text-danger">@traducaoHelper["TEM_CERTEZA_QUE_DESEJA_EXLUIR_ESTE_ITEM"]</h3>
            <hr />
            <dl class="dl-horizontal">
                <dt>@traducaoHelper["DESCRICAO"]</dt>
                <dd>
                    @Html.DisplayFor(model => model.Titulo)
                </dd>
                <dd>
                </dd>
            </dl>

            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()
                <div class="form-actions no-color">
                    <input type="submit" value="@traducaoHelper["EXCLUIR"]" class="btn btn-danger" id="confirm_button" />
                </div>
            }
        </div>
    </div>
</div>

Univer/Application/Adm/Views/Avisos/Details.cshtml
@model Core.Entities.Aviso
@using System.Linq;
@using Sistema.Models;
@using System.Collections.Generic;

@{
    var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
    ViewBag.Title = traducaoHelper["DETALHES"];
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="portlet box grey-gallery">

    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-book "></i>@traducaoHelper["DETALHES"]
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"></a>
        </div>
    </div>

    <div class="portlet-body form">

        <div class="form-body">
            <div class="row">
                <div class="col-md-10"><h4>@traducaoHelper["ATIVOS"]</h4></div>
                <div class="col-md-2">
                    @Html.ActionLink("Back to List", "Index", new { id = 0 }, new { @class = "Voltar pull-right", title = traducaoHelper["VOLTAR_PARA_A_LISTA"] })
                    @Html.ActionLink("Edit", "create", new { id = Model.ID }, new { @class = "Editar pull-right", title = traducaoHelper["EDITAR"] })
                </div>
            </div>
            <hr />
            <dl class="dl-horizontal">
                <dt>@traducaoHelper["TITULO"]</dt>
                <dd>
                    @Html.DisplayFor(model => model.Titulo)
                </dd>
                <dd>
                </dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>@traducaoHelper["DESCRICAO"]</dt>
                <dd>
                    @Html.DisplayFor(model => model.Texto)
                </dd>
                <dd>
                </dd>
            </dl>
            <dl class="dl-horizontal">
                <dt>@traducaoHelper["URGENTE"]</dt>
                @{
                    if (Model.Urgente)
                    {
                        <dd>@traducaoHelper["SIM"]</dd>
                    }
                    else
                    {
                        <dd>@traducaoHelper["NAO"]</dd>
                    }
                }
                <dd>
                </dd>
            </dl>

            <dl class="dl-horizontal">
                <dt>@traducaoHelper["INICIO"] / @traducaoHelper["FIM"]</dt>

                @{
                    if (Model.DataInicio.HasValue)
                    {
                        <dd>@Model.DataInicio e @Model.DataFim</dd>
                    }
                    else
                    {
                        <dd>-</dd>
                    }
                }

                <dd>
                </dd>
            </dl>

            <dl class="dl-horizontal">
                <dt>@traducaoHelper["USUARIOS"]</dt>
                <dd>

                    @{
                        if (ViewBag.UsuariosIDs != null && ((List<ItemViewModel>)ViewBag.UsuariosIDs).Any())
                        {
                            <ul>
                                @foreach (var item in ViewBag.UsuariosIDs)
                                {
                                    <li>@item.Name</li>
                                }
                            </ul>
                        }
                        else
                        {
                            @traducaoHelper["TODOS"]
                        }
                    }


                </dd>
                <dd>
                </dd>
            </dl>

        </div>
    </div>
</div>

Univer/Application/Adm/Views/Avisos/Edit.cshtml
@model Core.Entities.Ativo

@{
    var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
    ViewBag.Title = traducaoHelper["EDITAR"];
    Layout = "~/Views/Shared/_Layout.cshtml";

}

<div class="portlet box grey-gallery">

    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-pencil"></i>@traducaoHelper["EDITAR"]
        </div>
        <div class="tools">
            <a href="javascript:;" class="collapse"></a>
        </div>
    </div>

    <div class="portlet-body form">
        <!-- BEGIN FORM-->
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            <div class="form-body">
                <div class="form-horizontal">
                    <div class="row">
                        <div class="col-md-10"><h4>@traducaoHelper["ATIVOS"]</h4></div>
                        <div class="col-md-2">@Html.ActionLink("Back to List", "Index", new { id = 0 }, new { @class = "Voltar pull-right", title = traducaoHelper["VOLTAR_PARA_A_LISTA"] })</div>
                    </div>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.ID)

                    <div class="form-group">
                        <label class="control-label col-md-2" for="atualizacao">@traducaoHelper["DESCRICAO"]</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Descricao, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="@traducaoHelper["SALVAR"]" class="btn green-haze" />
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>

</div>

Univer/Application/Adm/Views/Avisos/Index.cshtml
@model PagedList.IPagedList<Core.Entities.Aviso>
@using PagedList.Mvc;

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var traducaoHelper = (Core.Helpers.TraducaoHelper)ViewBag.TraducaoHelper;
}

<div class="portlet box grey-gallery">

    <div class="portlet-title">
        <div class="caption"><i class="fa fa-reorder"></i> @traducaoHelper["AVISO"]</div>
        <div class="tools">
            <a href="javascript:;" class="collapse" title="@traducaoHelper["FECHAR"]" />
        </div>
        <div class="actions">
            <a href='@Url.Action("Create", "Avisos")' class="btn green-meadow">
                <i class="fa fa-plus"></i> @traducaoHelper["NOVO"]
            </a>

            <label>&nbsp;</label>
        </div>
    </div>

    <div class="portlet-body">

        <div class="table-toolbar">
            <div class="row">
                <div class="col-md-4">
                    <div class="form-group">
                        <div class="input-group">
                            @using (Html.BeginForm("Index", "Avisos", FormMethod.Get))
                            {
                                @Html.DropDownList("NumeroPaginas", null, htmlAttributes: new { @class = "form-control input-small input-inline marginB05" })
                                <input class="btn purple form-control input-small input-inline fontPlaceHolderIcon" id="Atualizar" name="Atualizar" value="&#xf021; @traducaoHelper["ATUALIZAR"]" type="submit" />
                            }
                        </div>
                    </div>
                </div>
                <div class="col-md-8">
                    @using (Html.BeginForm("Index", "Avisos", FormMethod.Get))
                    {
                        <div class="form-group pull-right">
                            <div class="input-group">
                                @Html.TextBox("ProcuraDescricao", ViewBag.CurrentProcuraDescricao as string, new { @class = "form-control input-small input-inline fontPlaceHolderIcon marginB05", @placeholder = traducaoHelper["TITULO"] })
                                <input class="btn blue-madison form-control input-small input-inline fontPlaceHolderIcon" id="Procura" name="Procura" value="&#xf002; @traducaoHelper["PROCURAR"]" type="submit" />
                            </div>
                        </div>
                    }
                </div>
            </div>
            <div class="row">
                <div class="col-md-10">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, SortOrder = ViewBag.CurrentSort, CurrentProcuraDescricao = ViewBag.CurrentProcuraDescricao, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize }))
                </div>
                <div class="col-md-2">
                    <label class="pull-right">@traducaoHelper["PAG"] @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @traducaoHelper["DE"] @Model.PageCount &nbsp;</label>
                </div>
            </div>
        </div>

        <div class="table-scrollable">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>

                        <th scope="col" style="min-width:80px; width:80px;">&nbsp;@traducaoHelper["ACOES"]&nbsp;</th>
                        <th scope="col">
                            @Html.ActionLink(traducaoHelper["TITULO"], "Index", new { SortOrder = ViewBag.FirstSortParm, CurrentProcuraTitulo = ViewBag.CurrentProcuraTitulo, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize })
                            @switch ((string)ViewBag.CurrentSort.ToString())
                            {
                                case "Titulo":
                                    {<i class="fa fa-chevron-down"></i>}
                                    break;
                                case "Titulo_desc":
                                    {<i class="fa fa-chevron-up"></i>}
                                    break;
                            }
                        </th>
                        <th scope="col">@traducaoHelper["VIDEO"]</th>
                        <th scope="col">@traducaoHelper["TIPO"]</th>
                        <th scope="col">@traducaoHelper["URGENTE"]</th>
                        <th scope="col">@traducaoHelper["INICIO"]</th>
                        <th scope="col">@traducaoHelper["FIM"]</th>
                    </tr>
                </thead>
                <tfoot>
                    <tr>

                        <th scope="col" style="min-width:80px; width:80px;">&nbsp;@traducaoHelper["ACOES"]&nbsp;</th>
                        <th scope="col">
                            @Html.ActionLink(traducaoHelper["TITULO"], "Index", new { SortOrder = ViewBag.FirstSortParm, CurrentProcuraDescricao = ViewBag.CurrentProcuraDescricao, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize })
                            @switch ((string)ViewBag.CurrentSort.ToString())
                            {
                                case "Titulo":
                                    {<i class="fa fa-chevron-down"></i>}
                                    break;
                                case "Titulo_desc":
                                    {<i class="fa fa-chevron-up"></i>}
                                    break;
                            }
                        </th>
                        <th scope="col">@traducaoHelper["VIDEO"]</th>
                        <th scope="col">@traducaoHelper["TIPO"]</th>
                        <th scope="col">@traducaoHelper["URGENTE"]</th>
                        <th scope="col">@traducaoHelper["DATA_INICIO"]</th>
                        <th scope="col">@traducaoHelper["DATA_FIM"]</th>
                </tfoot>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.ActionLink("Edit", "Create", new { id = item.ID }, new { @class = "gridEdit", title = traducaoHelper["EDITAR"] })
                                @Html.ActionLink("Details", "Details", new { id = item.ID }, new { @class = "gridDetail", title = traducaoHelper["DETALHES"] })
                                @Html.ActionLink("Delete", "Delete", new { id = item.ID }, new { @class = "gridDelete", title = traducaoHelper["EXCLUIR"] })
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.Titulo)
                            </td>
                            <td align="center">
                                @if (!string.IsNullOrEmpty(item.Video))
                                {
                                    <img src="~/Content/img/icon/youtube.png" width="35" onclick="showVideo('@item.Titulo','@item.Video')" style="cursor:pointer" />
                                }
                                else
                                {
                                    <span>-</span>
                                }
                            </td>

                            <td>
                                @Html.DisplayFor(modelItem => item.AvisoTipo.Nome)
                            </td>
                            <td align="center">

                                @if(item.Urgente)
                                {
                                    <img src="~/Content/img/icon/check-64.png" width="20" />
                                }

                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DataInicio)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.DataFim)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

        <div class="row">
            <div class="border-gridFooter">
                <div class="col-md-10">
                    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, SortOrder = ViewBag.CurrentSort, CurrentProcuraDescricao = ViewBag.CurrentProcuraDescricao, NumeroPaginas = ViewBag.CurrentNumeroPaginas, PageSize = ViewBag.PageSize }))
                </div>
                <div class="col-md-2">
                    <label class="pull-right">@traducaoHelper["PAG"]  @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) @traducaoHelper["DE"]  @Model.PageCount &nbsp;</label>
                </div>
            </div>
        </div>
    </div>
</div>



<div id="video-modal" class="modal" data-easein="tada" data-easeout="rollOut" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h4 class="modal-title" id="titulo-video"></h4>
            </div>
            <div class="modal-body">
                <iframe id="iframe-video" width="420" height="315" src=""></iframe>
            </div>
        </div>
    </div>
</div>

@section pageScripts {


    <script type="text/javascript">

        function showVideo(titulo, url) {
            if (url) {
                $("#titulo-video").html(titulo);
                $("#iframe-video").attr("src", url);
                $('#video-modal').modal();
            }
        }

    </script>
}